# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Toolinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RealmSwift'
  pod 'Charts'

  # Pods for Toolinder

  target 'ToolinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToolinderUITests' do
    # Pods for testing
  end

end
