# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moeum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for moeum

  target 'moeumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moeumUITests' do
    # Pods for testing
  end

end
